CREATE DATABASE EXERCICIO1
USE EXERCICIO1 
CREATE TABLE CLIENTE (idCliente INTEGER NOT NULL PRIMARY KEY, NOME CHAR(30), ENDERECO CHAR(30))
CREATE TABLE GENERO (idGenero INTEGER NOT NULL PRIMARY KEY)
CREATE TABLE CATEGORIA (idCategoria INTEGER NOT NULL PRIMARY KEY, DESCRICAO CHAR(50))
CREATE TABLE FILME (idFilme INTEGER NOT NULL PRIMARY KEY, CONSTRAINT fk_Categoria FOREIGN KEY (idCategoria) REFERENCES CATEGORIA(idCategoria), FOREIGN KEY REFERENCES GENERO (idGenero), Nome Varchar(30) NOT NULL);
CREATE TABLE LOCACAO (idLocacao INTEGER NOT NULL PRIMARY KEY, CONSTRAINT FKCLIENTE FOREIGN KEY (idCliente) REFERENCES CLIENTE)
CREATE INDEX Xcategoria on CLIENTE(idCliente)
CREATE INDEX Xgenero on GENERO(idGenero)
CREATE INDEX Xfilme on FILME(idFilme)
CREATE INDEX Xlocacao on Locacao(idLocacao)
INSERT INTO FILME (idFilme, Nome) VALUES (1, 'STAR WARS'),(2, 'O CHAMADO'), (3, 'O King Leão')
INSERT INTO LOCACAO (idLocacao) VALUES (1),(2)
INSERT INTO CLIENTE (idCliente, NOME, ENDERECO) VALUES (1, 'RENAN', 'RUA BATATA'),(2,'SAMIR','OUTRA RUA')
INSERT INTO GENERO (idGenero) VALUES(1),(2)
INSERT INTO CATEGORIA (idCategoria, DESCRICAO) VALUES (1, 'UMA AVENTURA STAR WARS...'), (2, 'MORRE EM SETE DIAS AO ACESSAR O TELEFONE'), (3, 'Leãozin que faz todo mundo chora')
SELECT idCategoria from CATEGORIA where idCategoria >= 2 order by idCategoria DESC