CREATE DATABASE EXERCICIO3
USE EXERCICIO3
CREATE TABLE PROPRIETARIO (idProprietario INTEGER PRIMARY KEY, NOME CHAR(20), TELEFONE CHAR(11), EMAIL CHAR(20))
CREATE TABLE PRODUTO (idProduto INTEGER PRIMARY KEY, NOME CHAR(30), PRECO INTEGER)
CREATE TABLE DETALHE (idDetalhe INTEGER PRIMARY KEY, idProduto INTEGER FOREIGN KEY REFERENCES PRODUTO(idProduto))
CREATE TABLE VENDEDOR (idVendedor INTEGER PRIMARY KEY, NOME CHAR(30) NOT NULL, TELEFONE CHAR(11), EMAIL CHAR(40), idProprietario INTEGER FOREIGN KEY REFERENCES PROPRIETARIO(idProprietario))
CREATE TABLE PEDIDO (idPedido INTEGER PRIMARY KEY, idVendedor INTEGER FOREIGN KEY REFERENCES VENDEDOR(idVendedor))
INSERT INTO PROPRIETARIO (idProprietario, NOME, TELEFONE, EMAIL) VALUES (1, 'PUDIM', '118494759', 'pudimpudim@gmail.com')
INSERT INTO PRODUTO (idProduto, NOME, PRECO) VALUES (1, 'PANDA COOKIE', 50)
INSERT INTO DETALHE (idDetalhe) VALUES(1)
INSERT INTO PEDIDO (idPedido) VALUES(1)
INSERT INTO VENDEDOR (idVendedor, NOME, TELEFONE, EMAIL) VALUES (1, 'BATATA', '43058350683', 'batata@gmail.com')